name: RSpec

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
    name: Tests on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - run: |
          source .envrc
          bundle exec rspec --format documentation --force-color

